#!/bin/bash

rm -f Makefile.am;
echo '
#+------------------------------------------------------------------------+
#| Description:  Magic Set Editor - Program to make Magic (tm) cards      |
#| Copyright:    (C) 2001 - 2008 Twan van Laarhoven and "coppro"          |
#| License:      GNU General Public License 2 or later (see file COPYING) |
#+------------------------------------------------------------------------+

# This file is generated by MakeAM.sh. DO NOT EDIT! -*- buffer-read-only: t -*-

# This flag allows us to use subdirectories:
AUTOMAKE_OPTIONS = 1.9 subdir-objects foreign

bin_PROGRAMS = magicseteditor
AM_CXXFLAGS = @WX_CXXFLAGS@ $(BOOST_CXXFLAGS) -I. -Wall
AM_LDFLAGS  = $(BOOST_LDFLAGS)

.hpp.gch:
	target=`echo $@ | sed "s|.gch$$|.hpp|"`;\
	depbase=`echo $$target | sed "s|[^/]*\$$|$(DEPDIR)/&|;s|\\.hpp\$$||"`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpch -x c++-header -c $$target &&\
	$(am__mv) $$depbase.Tpch $$depbase.Pch
	touch $@
.gch.o:
	gcc -x c - -c -o $@ <<<""

magicseteditor_LDADD = @WX_LIBS@ $(BOOST_REGEX_LIB)
magicseteditor_CXXFLAGS = $(AM_CXXFLAGS)
magicseteditor_SOURCES = 

SUBDIRS = po

EXTRA_DIST = build_aux/config.rpath m4/ChangeLog

DISTCLEANFILES = *~ autoscan.log build_aux/*~ m4/*~

if GLIBCPP_BUILD_PCH
clean-local:
	rm -f ./src/util/prec.hpp.gch
	rm -f ./src/util/prec.gch
include ./src/util/$(DEPDIR)/prec.Pch
magicseteditor_SOURCES += ./src/util/prec.gch
magicseteditor_CXXFLAGS += -fpch-deps
endif

distclean-local:
	-rm -rf autom4te.cache || rmdir autom4te.cache

# The script used to generate this list of sources is MakeAM.sh' > Makefile.am;

find . -name *.cpp | sed "s/\./magicseteditor_SOURCES += ./" >> Makefile.am;

if [ -d ./m4 ]; then
	echo "ACLOCAL_AMFLAGS = -I m4 --install" >> Makefile.am
fi

